### ISSUE TITLE
monadlib 0.2 not on OPAM

### ISSUE THREAD

**Issue by zepalmer** [Chattered/ocaml-monad#1]
Hello,

We're using this library for an OCaml project and have just encountered a bug in `monadlib` 0.1: sequence seems to reverse the order of elements in the list.  We believe this is caused by a bug you've already fixed, but the latest version of `monadlib` on OPAM is 0.1.  Has 0.2 been released under a different name?  If not, is there a reason it hasn't been released?  May I bother you to do the opam-publish?

Our thanks for the excellent library!  It's been very helpful.

**Comment by Chattered** [comment]
Glad you like it! I've pushed 0.2 to opam-repository.

There are some incompatibilities that this introduces, I'm afraid, so 0.1 is still there.

There are obvious directions to take the library in terms of abstraction, but they'll likely introduce more breaking changes.
