### ISSUE TITLE
`guard` should have a different signature

### ISSUE THREAD

**Issue by mwnx** [Chattered/ocaml-monad#2]
Hello,

I've started to use your library for some OCaml projects of mine (which is really nice to have by the way, coming from Haskell).
One thing that seems strange to me is the `guard` function's signature. It is currently `bool -> 'a m -> 'a m`, but I would expect `bool -> unit m`. Two reasons:
- The second is simpler but just as powerful, and conforms to Haskell's `guard` function.
- And more importantly for OCaml, the first one will evaluate its argument regardless of the value of the boolean (since OCaml is strict), which is bad from a performance point of view, and worse still if using monad notation to work with mutable structures such as streams.

Therefore, maybe you could consider changing this if it does not break too many things for other users.

**Comment by Chattered** [comment]
Hi mwnx. I agree with your comments, and would prefer to keep close to the Haskell APIs where the evaluation model allows. I will update this, unless you have a pull request ready to go.
